# Generated by Django 4.2.7 on 2025-08-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Tashkilot')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Lavozim')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nashr sarlavhasi (masalan, 7-son, 2025)')),
                ('cover_image', models.ImageField(upload_to='covers/', verbose_name='Muqova rasmi')),
                ('pdf_file', models.FileField(upload_to='issues/', verbose_name="To'liq nashr (PDF)")),
                ('published_date', models.DateField(verbose_name='Chop etilgan sana')),
                ('is_current', models.BooleanField(default=False, verbose_name='Joriy nashrmi?')),
            ],
            options={
                'verbose_name': 'Nashr (son)',
                'verbose_name_plural': 'Nashrlar (sonlar)',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Jurnal nomi')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='Qisqa nomi (masalan, QX yoki AI)')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "Kalit so'z",
                'verbose_name_plural': "Kalit so'zlar",
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentIssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha (masalan, 2024 - №4)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('link_to_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.issue', verbose_name="Bog'langan nashr")),
            ],
            options={
                'verbose_name': "So'nggi nashr havolasi",
                'verbose_name_plural': "So'nggi nashr havolalari",
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.journal', verbose_name='Jurnal'),
        ),
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('position_description', models.TextField(verbose_name='Lavozimi va tavsifi')),
                ('role', models.CharField(choices=[('bosh_muharrir', 'Bosh muharrir'), ('masul_kotib', "Mas'ul kotib"), ('hayat_azosi', "Hay'at a'zosi")], max_length=50, verbose_name='Roli')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='api.journal', verbose_name='Jurnal')),
            ],
            options={
                'verbose_name': "Tahririyat a'zosi",
                'verbose_name_plural': "Tahririyat a'zolari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('pages', models.CharField(max_length=50, verbose_name='Sahifalar')),
                ('references', models.TextField(blank=True, verbose_name='Foydalanilgan adabiyotlar')),
                ('article_file', models.FileField(blank=True, null=True, upload_to='articles/', verbose_name='Maqola fayli (PDF)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('authors', models.ManyToManyField(related_name='articles', to='api.author', verbose_name='Mualliflar')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.issue', verbose_name='Nashr')),
                ('keywords', models.ManyToManyField(blank=True, to='api.keyword', verbose_name="Kalit so'zlar")),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['pages'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=2, verbose_name='Til')),
                ('title', models.CharField(max_length=500, verbose_name='Maqola nomi')),
                ('abstract', models.TextField(verbose_name='Annotatsiya')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.article')),
            ],
            options={
                'verbose_name': 'Maqola tarjimasi',
                'verbose_name_plural': 'Maqola tarjimalari',
                'unique_together': {('article', 'language')},
            },
        ),
    ]
